platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'WazoReactNativeDemo' do
  rn_prefix = "../node_modules/react-native"
  permissions_path = '../node_modules/react-native-permissions/ios'

  # React Native and its dependencies
  pod 'FBLazyVector', :path => "#{rn_prefix}/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "#{rn_prefix}/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "#{rn_prefix}/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "#{rn_prefix}/Libraries/TypeSafety"
  pod 'React', :path => "#{rn_prefix}/"
  pod 'React-Core', :path => "#{rn_prefix}/"
  pod 'React-CoreModules', :path => "#{rn_prefix}/React/CoreModules"
  pod 'React-RCTActionSheet', :path => "#{rn_prefix}/Libraries/ActionSheetIOS"
  pod 'React-RCTAnimation', :path => "#{rn_prefix}/Libraries/NativeAnimation"
  pod 'React-RCTBlob', :path => "#{rn_prefix}/Libraries/Blob"
  pod 'React-RCTImage', :path => "#{rn_prefix}/Libraries/Image"
  pod 'React-RCTLinking', :path => "#{rn_prefix}/Libraries/LinkingIOS"
  pod 'React-RCTNetwork', :path => "#{rn_prefix}/Libraries/Network"
  pod 'React-RCTSettings', :path => "#{rn_prefix}/Libraries/Settings"
  pod 'React-RCTText', :path => "#{rn_prefix}/Libraries/Text"
  pod 'React-RCTVibration', :path => "#{rn_prefix}/Libraries/Vibration"
  pod 'React-Core/RCTWebSocket', :path => "#{rn_prefix}/"
  pod 'React-Core/DevSupport', :path => "#{rn_prefix}/"
  pod 'React-cxxreact', :path => "#{rn_prefix}/ReactCommon/cxxreact"
  pod 'React-jsi', :path => "#{rn_prefix}/ReactCommon/jsi"
  pod 'React-jsiexecutor', :path => "#{rn_prefix}/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{rn_prefix}/ReactCommon/jsinspector"
  pod 'ReactCommon/jscallinvoker', :path => "#{rn_prefix}/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "#{rn_prefix}/ReactCommon"
  pod 'Yoga', :path => "#{rn_prefix}/ReactCommon/yoga"
  pod 'DoubleConversion', :podspec => "#{rn_prefix}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_prefix}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_prefix}/third-party-podspecs/Folly.podspec"

  # Other native modules
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'react-native-webrtc', :path => "../node_modules/react-native-webrtc"
  pod 'RNVoipPushNotification', :path => "../node_modules/react-native-voip-push-notification"

  # Automatically detect installed unimodules
  use_unimodules!

  # react-native-cli autolinking
  use_native_modules!
end
